### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by seb-le** [jsczzzk/R-MSFM#1]
Hi, First, thank you for your nice work.

I have an issue when I try to download the provided pretrained model.

As I access the download link, the Baidu account is required for download,

but I cannot register the Baidu account in my country.

How can I download it?

thank you.

**Comment by jsczzzk** [comment]
Hi, we update the README to provide the pretrained models from google drive.

**Comment by seb-le** [comment]
I appreciate your kindness.

Thank you!
