### ISSUE TITLE
Different depth performance

### ISSUE THREAD

**Issue by seb-le** [jsczzzk/R-MSFM#4]
Hi,

First, thank you for your nice work.

I have a question about measuring depth performance.

I downloaded and tested 6M.zip provided on google drive.

I used the test code of monodepth2 to evaluate the model.

However, there are slightly different depth results with the paper.

In paper:
0.112    0.806    **4.704    0.191    0.878**    0.960    0.981

In my test:
0.112    0.806    **4.705    0.192    0.877**    0.960    0.981

Are there any changes in the evaluation code of monodepth2?

Thank you.

**Comment by jsczzzk** [comment]
Hi, 
I also used the evaluation code of Monodepth2. This slight difference may be related to the environment.

**Comment by seb-le** [comment]
Thank you for your quick response!
