### ISSUE TITLE
Model parameters

### ISSUE THREAD

**Issue by liusiping10** [jsczzzk/R-MSFM#5]
How to calculate the model parameters (3.8M) in the paper? I can't get this result by using thop.

**Comment by jsczzzk** [comment]
I also use thop library to calculate the model parameters. For our R-MSFM6 model, the model parameters are 3815044.

**Comment by liusiping10** [comment]
Could you share the calculation code?

I got the results with:
input size: 1, 3, 192, 640
encoder = networks.ResnetEncoder(18, False)

depth_decoder = R_MSFM3()
total FLOPs = 13586288642 
total Prameters = 14525804

depth_decoder = R_MSFM6()
total FLOPs = 23947468802 FLOPs
total Prameters = 14821484

**Comment by liusiping10** [comment]
Sorry, I use sum([param.nelement() for param in model.parameters()])), and get total Prameters = 14821484

**Comment by jsczzzk** [comment]
If you use this method above, the parameters of the last two layers of resnet will be included. Indeed, you should use the following method:
`from thop import profile `
`flops, params = profile(model, inputs=(input, )`

**Comment by liusiping10** [comment]
Thanks a lot.
