### ISSUE TITLE
BasicUpdateBlock

### ISSUE THREAD

**Issue by Rashfu** [jsczzzk/R-MSFM#6]
The param `net` passed to the [forward](https://github.com/jsczzzk/R-MSFM/blob/main/core/update.py#L106) function seems useless, because it's always covered by the result of `self.encoder(depth, corr)`. Is it a bug here or just as what I think?

**Comment by jsczzzk** [comment]
Yes, it is just as what you think. Because  we try to apply the GRU module to the BasicUpdateBlock, i.e., R-MSFM3-B in Table2.
