### ISSUE TITLE
a few doubts

### ISSUE THREAD

**Issue by zsh1223** [jsczzzk/R-MSFM#9]
I think your work is very meaningful, but I have a few doubts
① Is the code you provided R-MSFM3-A, R-MSFM3-B, R-MSFM3-C, or R-MSFM3-D? I couldn't find the M3SFM module in your code repository. Can you provide it? How can I obtain these 4 variants?
② In your code, the reported model parameter count is only depthnet. Or is it the network model parameter count of your posenet and depthnet combined?
③ Do you think there are any benefits to changing the use of renset18, which shares parameters with depthnet in monodeep2, to using 7-layer CNN in posenet? Does this change reduce the number of parameters or improve accuracy?

**Comment by jsczzzk** [comment]
Apologies for the delayed response. 
1. R-MSFM3-C corresponds to the R-MSFM module used in this project.
2. The other variants (R-MSFM3-A, R-MSFM3-B, and R-MSFM3-D) are part of our ablation experiments. You can construct the relevant models by following the provided instructions.
3. The MSFM module utilized is the Class SepConvGRU.
4. The reported model parameter count pertains solely to the depthnet.
5. I have not conducted experiments on replacing ResNet18 with a 7-layer CNN in PoseNet. However, it might be a worthwhile experiment for you to explore potential reductions in parameter count or improvements in accuracy.
